export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Another Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge("bg-background", inter.className)}
      >
        {children}
      </body>
    </html>
  );
}
